default: &default
  adapter: mysql2
  charset: utf8
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost
  
development:
  adapter: mysql2
  charset: utf8
  encoding: utf8
  database: development
  pool: 5
  username: root
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  charset: utf8
  encoding: utf8
  database: _test
  pool: 5
  username: 
  password:
  host: localhost

production:
  adapter: mysql2
  charset: utf8
  encoding: utf8
  database: _production
  pool: 5
  username: 
  password: 
  host: localhost